-- Create users table
create table if not exists users (
  id uuid default uuid_generate_v4() primary key,
  email text unique not null,
  password_hash text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create notes table
create table if not exists notes (
  id bigint generated by default as identity primary key,
  user_id uuid references users(id) not null,
  title text not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table users enable row level security;
alter table notes enable row level security;

-- Create policies (Optional for this simple app as we handle auth in backend, 
-- but good practice if using Supabase client on frontend directly. 
-- For now, we allow the service role (backend) to do everything)
